spring:
  application:
    name: DiscoveryService
server:
  port: 8761
eureka:
  server:
    enable-self-preservation: false
  client:
    fetch-registry: false
    register-with-eureka: false
management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true